version: '3.7'
services:
  web:
      build: ./
      command: python django/manage.py runserver
      volumes:
        - ./PYTHON_JOB_WEBSITE/:/usr/src/PYTHON_JOB_WEBSITE/
      ports:
        - 8000:8000
      env_file:
        - ./.env
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    env_file:
      - ./.env
  
volumes:
  postgres_data: