version: '3.7'
services:
  django:
    build: ./
    command: [sh, -c, "python django/manage.py migrate && 
                       python django/manage.py runserver 0.0.0.0:8000"]
    volumes:
      - ./PYTHON_JOB_WEBSITE/:/usr/src/PYTHON_JOB_WEBSITE/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on: 
      - db

  parser:
    build: ./
    command: tail -F anything
    env_file:
      - ./.env

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      # https://www.postgresql.org/docs/current/libpq-envars.html, подгружаются из .env
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    env_file:
      - ./.env
  
volumes:
  postgres_data: